### ISSUE TITLE
URGENT: Breaking changes in v1.3

### ISSUE THREAD

**Issue by timofei-iatsenko** [MartinCerny-awin/pseudolocale#25]
The v1.3 sources is completely different from previous versions. I mentioned that in [this issue](https://github.com/MartinCerny-awin/pseudolocale/issues/17) a few times.  
You have 400k downloads per week and it's definitely a bad thing for them. The package managers could simply resolve to this version because it satsifies the semver `"^1.1.0"` and results in a broken application.

That changes should have been pushed as major release, such as v2.  

Since npm releases are immutable, and you could not change what was already pushed, I propose push 1.4 release which actually would be a copy of `1.1` to satisfy semver and then publish current repo state as v2.

**Comment by paales** [comment]
1.2.0 would be better I guess: https://www.npmjs.com/package/pseudolocale/v/1.2.0.

Getting questions about the issue on our Slack:

![Scherm­afbeelding 2023-04-05 om 13 24 56](https://user-images.githubusercontent.com/1244416/230066823-a79112eb-eae3-49ae-a2b0-2bf41dfa3270.png)

**Comment by antonio-wundermart** [comment]
HI @thekip, as workaround for any other affected dependency (including linguijs), I installed in my projects
npm install pseudolocale@1.2.0
Apparently it's working, although is just a workaround.

**Comment by timofei-iatsenko** [comment]
FYI https://github.com/lingui/js-lingui/pull/1583

**Comment by paales** [comment]
@antonio-wundermart The pseudolocale package is used as a dependency of @lingui/cli which has set the version to `"^1.1.0"`, this means that it is not trivial to get the right version, without upgrading @lingui/cli. This would mean an additional release of our package. Would be better if this could be fixed.

Tagging @MartinCerny-awin for the case he hasn't seen this issue yet.

Workaround for now, add the following to your  package.json (works with yarn, not sure about other package managers):

``` 
  "resolutions": {
    "pseudolocale": "1.2.0"
  },
```

**Comment by antonio-wundermart** [comment]
> @antonio-wundermart The pseudolocale package is used as a dependency of @lingui/cli which has set the version to `"^1.1.0"`, this means that it is not trivial to get the right version, without upgrading @lingui/cli. This would mean an additional release of our package. Would be better if this could be fixed.
> 
> Tagging @MartinCerny-awin for the case he hasn't seen this issue yet.
> 
> Workaround for now, add the following to your package.json (works with yarn, not sure about other package managers):
> 
> ```
>   "resolutions": {
>     "pseudolocale": "1.2.0"
>   },
> ```

Thank you, this is exactly what I was looking for.

**Comment by MartinCerny-awin** [comment]
Sorry guys, I have just released 1.4.0 which should be same as 1.2.0 Let me know if it fixes the issue for you.

I will then go and release 1.3.0 as 2.0.0

**Comment by paales** [comment]
@MartinCerny-awin I can confirm it works as expected. Thanks a lot for the prompt response!
